# Generated by Django 6.0.5 on 2026-05-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoria',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='monitorias/'),
        ),
    ]
