# Generated by Django 6.0.5 on 2026-05-11 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0002_monitoria_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='monitoria',
            name='benefit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='beneficio_monitoria', to='monitorias.beneficio'),
            preserve_default=False,
        ),
    ]
