# Generated by Django 6.0.5 on 2026-05-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0003_beneficio_monitoria_benefit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoria',
        ),
    ]
