# Generated by Django 6.0.5 on 2026-05-14 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0005_monitoria_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoria',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='monitorias', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
