# Generated by Django 6.0.5 on 2026-05-15 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0006_alter_monitoria_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20)),
                ('monitoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='monitorias.monitoria')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('monitoria', 'email'), name='unique_inscricao_monitoria_email')],
            },
        ),
    ]
