# Generated by Django 6.0.5 on 2026-05-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0007_inscricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='status',
        ),
    ]
