# Generated by Django 6.0.5 on 2026-05-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0008_remove_inscricao_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoria',
            old_name='benefit',
            new_name='beneficio',
        ),
        migrations.RenameField(
            model_name='monitoria',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='monitoria',
            old_name='date',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='monitoria',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='monitoria',
            old_name='photo',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='monitoria',
            old_name='owner',
            new_name='proprietario',
        ),
        migrations.RenameField(
            model_name='monitoria',
            old_name='title',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='monitoria',
            name='vagas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
