# Generated by Django 6.0.5 on 2026-05-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0009_rename_benefit_monitoria_beneficio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoria',
            old_name='proprietario',
            new_name='owner',
        ),
    ]
