# Generated by Django 6.0.5 on 2026-05-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0010_rename_proprietario_monitoria_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficio',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='nome',
        ),
    ]
