# Generated by Django 6.0.5 on 2026-05-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0011_rename_name_beneficio_nome_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inscricao',
            name='unique_inscricao_monitoria_email',
        ),
        migrations.AddConstraint(
            model_name='inscricao',
            constraint=models.UniqueConstraint(fields=('monitoria', 'email'), name='inscricao_unica_monitoria_email'),
        ),
    ]
