# Generated by Django 6.0.5 on 2026-05-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0012_remove_inscricao_unique_inscricao_monitoria_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoria',
            name='foto',
        ),
    ]
