# Generated by Django 6.0.5 on 2026-05-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0013_remove_monitoria_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoria',
            old_name='owner',
            new_name='monitor',
        ),
    ]
