# Generated by Django 6.0.5 on 2026-05-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0014_rename_owner_monitoria_monitor'),
    ]

    operations = [
    ]
